// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const AdditionalPropertiesChoice1Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The primitive type, if any
 */
export type AdditionalPropertiesChoice1Of5Type = (typeof AdditionalPropertiesChoice1Of5Type)[keyof typeof AdditionalPropertiesChoice1Of5Type];

export const AdditionalPropertiesChoice5Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the union, if any
 */
export type AdditionalPropertiesChoice5Of5Type = (typeof AdditionalPropertiesChoice5Of5Type)[keyof typeof AdditionalPropertiesChoice5Of5Type];

export const Choice1Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The primitive type, if any
 */
export type Choice1Of5Type = (typeof Choice1Of5Type)[keyof typeof Choice1Of5Type];

export const Choice5Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the union, if any
 */
export type Choice5Of5Type = (typeof Choice5Of5Type)[keyof typeof Choice5Of5Type];

export const EnumTypeSpecPropertiesType = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the enum
 */
export type EnumTypeSpecPropertiesType = (typeof EnumTypeSpecPropertiesType)[keyof typeof EnumTypeSpecPropertiesType];

export const InputPropertiesAdditionalPropertiesChoice5Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the union, if any
 */
export type InputPropertiesAdditionalPropertiesChoice5Of5Type = (typeof InputPropertiesAdditionalPropertiesChoice5Of5Type)[keyof typeof InputPropertiesAdditionalPropertiesChoice5Of5Type];

export const OneOf0PropertiesType = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The primitive type, if any
 */
export type OneOf0PropertiesType = (typeof OneOf0PropertiesType)[keyof typeof OneOf0PropertiesType];

export const OneOf4PropertiesType = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the union, if any
 */
export type OneOf4PropertiesType = (typeof OneOf4PropertiesType)[keyof typeof OneOf4PropertiesType];

export const PropertiesAdditionalPropertiesChoice1Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The primitive type, if any
 */
export type PropertiesAdditionalPropertiesChoice1Of5Type = (typeof PropertiesAdditionalPropertiesChoice1Of5Type)[keyof typeof PropertiesAdditionalPropertiesChoice1Of5Type];

export const PropertiesAdditionalPropertiesChoice5Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the union, if any
 */
export type PropertiesAdditionalPropertiesChoice5Of5Type = (typeof PropertiesAdditionalPropertiesChoice5Of5Type)[keyof typeof PropertiesAdditionalPropertiesChoice5Of5Type];

export const PropertiesType = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The primitive type, if any
 */
export type PropertiesType = (typeof PropertiesType)[keyof typeof PropertiesType];

export const Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The primitive type, if any
 */
export type Type = (typeof Type)[keyof typeof Type];

export const TypeSpecOneOf0PropertiesType = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The primitive type, if any
 */
export type TypeSpecOneOf0PropertiesType = (typeof TypeSpecOneOf0PropertiesType)[keyof typeof TypeSpecOneOf0PropertiesType];

export const TypeSpecOneOf4PropertiesType = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the union, if any
 */
export type TypeSpecOneOf4PropertiesType = (typeof TypeSpecOneOf4PropertiesType)[keyof typeof TypeSpecOneOf4PropertiesType];

export const VariablesAdditionalPropertiesChoice5Of5Type = {
    Boolean: "boolean",
    Integer: "integer",
    Number: "number",
    String: "string",
} as const;

/**
 * The underlying primitive type of the union, if any
 */
export type VariablesAdditionalPropertiesChoice5Of5Type = (typeof VariablesAdditionalPropertiesChoice5Of5Type)[keyof typeof VariablesAdditionalPropertiesChoice5Of5Type];
