# configuration file for dotnet-releaser
profile = "custom"
[msbuild]
project = "JsonSchema.sln"
[nuget]
publish = false
[brew]
publish = false
[scoop]
publish = false
[github]
user = "Frassle"
repo = "pulumi-jsonschema"
version_prefix = "v"
[[pack]]
rid = ["win-x64", "win-arm64", "linux-x64", "linux-arm64", "osx-x64", "osx-arm64"]
kinds = ["tar"]
renamer = [
	{ pattern = "\\.(\\d+\\.\\d+\\.\\d+)\\.", replace = "-v$1-"},
	{ pattern = "x64", replace = "amd64"},
	{ pattern = "win", replace = "windows"},
	{ pattern = "osx", replace = "darwin"}
]