// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bootstraprc.Outputs
{

    [OutputType]
    public sealed class CoreProperties
    {
        public readonly ImmutableDictionary<string, object>? AdditionalProperties;
        /// <summary>
        /// Import your custom styles here. Usually this endpoint file contains a list of @imports of your application styles.
        /// </summary>
        public readonly string? AppStyles;
        /// <summary>
        /// The .scss file path to be loaded after Bootstrap's _variables.scss file
        /// </summary>
        public readonly string? BootstrapCustomizations;
        public readonly Pulumi.Bootstraprc.BootstrapVersion BootstrapVersion;
        public readonly Pulumi.Bootstraprc.Loglevel? Loglevel;
        /// <summary>
        /// The .scss file path to be loaded before Bootstrap's _variables.scss file
        /// </summary>
        public readonly string? PreBootstrapCustomizations;
        /// <summary>
        /// unhandled schema: Json.Schema.DescriptionKeyword, Json.Schema.TypeKeyword
        /// </summary>
        public readonly object? Scripts;
        /// <summary>
        /// An array of Webpack loader names. Order matters, and sass-loader is required.
        /// </summary>
        public readonly ImmutableArray<string> StyleLoaders;
        /// <summary>
        /// unhandled schema: Json.Schema.DescriptionKeyword, Json.Schema.TypeKeyword
        /// </summary>
        public readonly object? Styles;
        /// <summary>
        /// Set to true if using a custom icon font and you need to specify its path in your Sass files
        /// </summary>
        public readonly bool? UseCustomIconFontPath;
        /// <summary>
        /// Enables/disables the flexbox model available in Bootstrap 4
        /// </summary>
        public readonly bool? UseFlexbox;

        [OutputConstructor]
        private CoreProperties(
            ImmutableDictionary<string, object>? additionalProperties,

            string? appStyles,

            string? bootstrapCustomizations,

            Pulumi.Bootstraprc.BootstrapVersion bootstrapVersion,

            Pulumi.Bootstraprc.Loglevel? loglevel,

            string? preBootstrapCustomizations,

            object? scripts,

            ImmutableArray<string> styleLoaders,

            object? styles,

            bool? useCustomIconFontPath,

            bool? useFlexbox)
        {
            AdditionalProperties = additionalProperties;
            AppStyles = appStyles;
            BootstrapCustomizations = bootstrapCustomizations;
            BootstrapVersion = bootstrapVersion;
            Loglevel = loglevel;
            PreBootstrapCustomizations = preBootstrapCustomizations;
            Scripts = scripts;
            StyleLoaders = styleLoaders;
            Styles = styles;
            UseCustomIconFontPath = useCustomIconFontPath;
            UseFlexbox = useFlexbox;
        }
    }
}
