// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// Describes an object or enum type.
    /// </summary>
    public sealed class TypeDefinitionArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalProperties")]
        private InputMap<object>? _additionalProperties;
        public InputMap<object> AdditionalProperties
        {
            get => _additionalProperties ?? (_additionalProperties = new InputMap<object>());
            set => _additionalProperties = value;
        }

        [Input("choice1Of2")]
        public Input<Inputs.ObjectTypeDefinitionArgs>? Choice1Of2 { get; set; }

        [Input("choice2Of2")]
        public Input<Inputs.EnumTypeDefinitionArgs>? Choice2Of2 { get; set; }

        /// <summary>
        /// The description of the type, if any. Interpreted as Markdown.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Indicates that the implementation of the type should not be generated from the schema, and is instead provided out-of-band by the package author
        /// </summary>
        [Input("isOverlay")]
        public Input<bool>? IsOverlay { get; set; }

        [Input("language")]
        private InputMap<object>? _language;

        /// <summary>
        /// Additional language-specific data about the type.
        /// </summary>
        public InputMap<object> Language
        {
            get => _language ?? (_language = new InputMap<object>());
            set => _language = value;
        }

        public TypeDefinitionArgs()
        {
        }
        public static new TypeDefinitionArgs Empty => new TypeDefinitionArgs();
    }
}
