// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * Read the given JSON into the object model
 */
export function read(args: ReadArgs, opts?: pulumi.InvokeOptions): Promise<ReadResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pulumi:index:read", {
        "json": args.json,
    }, opts, utilities.getPackage());
}

export interface ReadArgs {
    json: string;
}

export interface ReadResult {
    readonly value: outputs.PulumiPackageMetaschema;
}
/**
 * Read the given JSON into the object model
 */
export function readOutput(args: ReadOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<ReadResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pulumi:index:read", {
        "json": args.json,
    }, opts, utilities.getPackage());
}

export interface ReadOutputArgs {
    json: pulumi.Input<string>;
}
