// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

/**
 * Describes an object or resource property
 */
export interface AdditionalProperties {
    additionalProperties?: {[key: string]: any};
    choice1Of5?: inputs.Choice1Of2PropertiesAdditionalPropertiesChoice1Of5;
    choice2Of5?: inputs.Choice2Of5;
    choice3Of5?: inputs.MapType;
    choice4Of5?: inputs.NamedType;
    choice5Of5?: inputs.PropertiesAdditionalPropertiesChoice5Of5;
    const?: boolean | number | string;
    default?: boolean | number | string;
    defaultInfo?: inputs.DefaultInfo;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Additional language-specific data about the property.
     */
    language?: {[key: string]: any};
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: boolean;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: boolean;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: boolean;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: boolean;
}

/**
 * Describes an object or resource property
 */
export interface AdditionalPropertiesArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of5?: pulumi.Input<inputs.Choice1Of2PropertiesAdditionalPropertiesChoice1Of5Args>;
    choice2Of5?: pulumi.Input<inputs.Choice2Of5Args>;
    choice3Of5?: pulumi.Input<inputs.MapTypeArgs>;
    choice4Of5?: pulumi.Input<inputs.NamedTypeArgs>;
    choice5Of5?: pulumi.Input<inputs.PropertiesAdditionalPropertiesChoice5Of5Args>;
    const?: pulumi.Input<boolean | number | string>;
    default?: pulumi.Input<boolean | number | string>;
    defaultInfo?: pulumi.Input<inputs.DefaultInfoArgs>;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Additional language-specific data about the property.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: pulumi.Input<boolean>;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: pulumi.Input<boolean>;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: pulumi.Input<boolean>;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: pulumi.Input<boolean>;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface AdditionalPropertiesChoice1Of5 {
    type: enums.AdditionalPropertiesChoice1Of5Type;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface AdditionalPropertiesChoice1Of5Args {
    type: pulumi.Input<enums.AdditionalPropertiesChoice1Of5Type>;
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface AdditionalPropertiesChoice2Of5 {
    items: inputs.TypeSpec;
    type: "array";
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface AdditionalPropertiesChoice2Of5Args {
    items: pulumi.Input<inputs.TypeSpecArgs>;
    type: pulumi.Input<"array">;
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface AdditionalPropertiesChoice3Of5 {
    additionalProperties?: inputs.TypeSpec;
    type: "object";
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface AdditionalPropertiesChoice3Of5Args {
    additionalProperties?: pulumi.Input<inputs.TypeSpecArgs>;
    type: pulumi.Input<"object">;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface AdditionalPropertiesChoice5Of5 {
    discriminator?: inputs.Discriminator;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: inputs.TypeSpec[];
    type?: enums.OneOf4PropertiesType;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface AdditionalPropertiesChoice5Of5Args {
    discriminator?: pulumi.Input<inputs.DiscriminatorArgs>;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: pulumi.Input<pulumi.Input<inputs.TypeSpecArgs>[]>;
    type?: pulumi.Input<enums.OneOf4PropertiesType>;
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface AdditionalPropertiesInputPropertiesAdditionalPropertiesChoice3Of5 {
    additionalProperties?: inputs.InputPropertiesAdditionalProperties;
    type: "object";
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface AdditionalPropertiesInputPropertiesAdditionalPropertiesChoice3Of5Args {
    additionalProperties?: pulumi.Input<inputs.InputPropertiesAdditionalPropertiesArgs>;
    type: pulumi.Input<"object">;
}

export interface AliasDefinition {
    additionalProperties?: {[key: string]: any};
    /**
     * The name portion of the alias, if any
     */
    name?: string;
    /**
     * The project portion of the alias, if any
     */
    project?: string;
    /**
     * The type portion of the alias, if any
     */
    type?: string;
}

export interface AliasDefinitionArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * The name portion of the alias, if any
     */
    name?: pulumi.Input<string>;
    /**
     * The project portion of the alias, if any
     */
    project?: pulumi.Input<string>;
    /**
     * The type portion of the alias, if any
     */
    type?: pulumi.Input<string>;
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface ArrayType {
    items: inputs.VariablesAdditionalProperties;
    type: "array";
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface ArrayTypeArgs {
    items: pulumi.Input<inputs.VariablesAdditionalPropertiesArgs>;
    type: pulumi.Input<"array">;
}

export interface BaseProvider {
    /**
     * The unqualified name of the package (e.g. "aws", "azure", "gcp", "kubernetes", "random")
     */
    name: string;
    /**
     * The URL to use when downloading the provider plugin binary.
     */
    pluginDownloadURL?: string;
    /**
     * The version of the package. The version must be valid semver.
     */
    version: string;
}

export interface BaseProviderArgs {
    /**
     * The unqualified name of the package (e.g. "aws", "azure", "gcp", "kubernetes", "random")
     */
    name: pulumi.Input<string>;
    /**
     * The URL to use when downloading the provider plugin binary.
     */
    pluginDownloadURL?: pulumi.Input<string>;
    /**
     * The version of the package. The version must be valid semver.
     */
    version: pulumi.Input<string>;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface Choice1Of2PropertiesAdditionalPropertiesChoice1Of5 {
    type: enums.Choice1Of5Type;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface Choice1Of2PropertiesAdditionalPropertiesChoice1Of5Args {
    type: pulumi.Input<enums.Choice1Of5Type>;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface Choice1Of5 {
    type: enums.PropertiesType;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface Choice1Of5Args {
    type: pulumi.Input<enums.PropertiesType>;
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface Choice2Of5 {
    items: inputs.AdditionalProperties;
    type: "array";
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface Choice2Of5Args {
    items: pulumi.Input<inputs.AdditionalPropertiesArgs>;
    type: pulumi.Input<"array">;
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface Choice3Of5 {
    additionalProperties?: inputs.VariablesAdditionalProperties;
    type: "object";
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface Choice3Of5Args {
    additionalProperties?: pulumi.Input<inputs.VariablesAdditionalPropertiesArgs>;
    type: pulumi.Input<"object">;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface Choice5Of5 {
    discriminator?: inputs.Discriminator;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: inputs.InputPropertiesAdditionalProperties[];
    type?: enums.InputPropertiesAdditionalPropertiesChoice5Of5Type;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface Choice5Of5Args {
    discriminator?: pulumi.Input<inputs.DiscriminatorArgs>;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: pulumi.Input<pulumi.Input<inputs.InputPropertiesAdditionalPropertiesArgs>[]>;
    type?: pulumi.Input<enums.InputPropertiesAdditionalPropertiesChoice5Of5Type>;
}

/**
 * The package's configuration variables.
 */
export interface Config {
    /**
     * A list of the names of the package's non-required configuration variables.
     */
    defaults?: string[];
    /**
     * A map from variable name to propertySpec that describes a package's configuration variables.
     */
    variables?: {[key: string]: inputs.VariablesAdditionalProperties};
}

/**
 * The package's configuration variables.
 */
export interface ConfigArgs {
    /**
     * A list of the names of the package's non-required configuration variables.
     */
    defaults?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A map from variable name to propertySpec that describes a package's configuration variables.
     */
    variables?: pulumi.Input<{[key: string]: pulumi.Input<inputs.VariablesAdditionalPropertiesArgs>}>;
}

/**
 * Additional information about the property's default value, if any.
 */
export interface DefaultInfo {
    additionalProperties?: {[key: string]: any};
    /**
     * A set of environment variables to probe for a default value.
     */
    environment: string[];
    /**
     * Additional language-specific data about the default value.
     */
    language?: {[key: string]: any};
}

/**
 * Additional information about the property's default value, if any.
 */
export interface DefaultInfoArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * A set of environment variables to probe for a default value.
     */
    environment: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Additional language-specific data about the default value.
     */
    language?: pulumi.Input<{[key: string]: any}>;
}

/**
 * Informs the consumer of an alternative schema based on the value associated with it
 */
export interface Discriminator {
    additionalProperties?: {[key: string]: any};
    /**
     * An optional object to hold mappings between payload values and schema names or references
     */
    mapping?: {[key: string]: string};
    /**
     * PropertyName is the name of the property in the payload that will hold the discriminator value
     */
    propertyName: string;
}

/**
 * Informs the consumer of an alternative schema based on the value associated with it
 */
export interface DiscriminatorArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * An optional object to hold mappings between payload values and schema names or references
     */
    mapping?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * PropertyName is the name of the property in the payload that will hold the discriminator value
     */
    propertyName: pulumi.Input<string>;
}

/**
 * Describes an enum type
 */
export interface EnumTypeDefinition {
    /**
     * The list of possible values for the enum
     */
    enum: inputs.EnumValueDefinition[];
    type: enums.EnumTypeSpecPropertiesType;
}

/**
 * Describes an enum type
 */
export interface EnumTypeDefinitionArgs {
    /**
     * The list of possible values for the enum
     */
    enum: pulumi.Input<pulumi.Input<inputs.EnumValueDefinitionArgs>[]>;
    type: pulumi.Input<enums.EnumTypeSpecPropertiesType>;
}

export interface EnumValueDefinition {
    additionalProperties?: {[key: string]: any};
    /**
     * Indicates whether the value is deprecated.
     */
    deprecationMessage?: string;
    /**
     * The description of the enum value, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * If present, overrides the name of the enum value that would usually be derived from the value.
     */
    name?: string;
    value: boolean | number | number | string;
}

export interface EnumValueDefinitionArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates whether the value is deprecated.
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the enum value, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * If present, overrides the name of the enum value that would usually be derived from the value.
     */
    name?: pulumi.Input<string>;
    value: pulumi.Input<boolean | number | number | string>;
}

/**
 * Describes a function.
 */
export interface FunctionDefinition {
    additionalProperties?: {[key: string]: any};
    /**
     * Indicates whether the function is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the function, if any. Interpreted as Markdown.
     */
    description?: string;
    inputs?: inputs.ObjectTypeDetails;
    /**
     * Indicates that the implementation of the function should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: boolean;
    /**
     * Additional language-specific data about the function.
     */
    language?: {[key: string]: any};
    /**
     * A list of parameter names that determines whether the input bag should be treated as a single argument or as multiple arguments. The list corresponds to the order in which the parameters should be passed to the function.
     */
    multiArgumentInputs?: string[];
    /**
     * unhandled schema: Json.Schema.DescriptionKeyword, Json.Schema.AnyOfKeyword
     */
    outputs?: any;
}

/**
 * Describes a function.
 */
export interface FunctionDefinitionArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates whether the function is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the function, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    inputs?: pulumi.Input<inputs.ObjectTypeDetailsArgs>;
    /**
     * Indicates that the implementation of the function should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: pulumi.Input<boolean>;
    /**
     * Additional language-specific data about the function.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * A list of parameter names that determines whether the input bag should be treated as a single argument or as multiple arguments. The list corresponds to the order in which the parameters should be passed to the function.
     */
    multiArgumentInputs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * unhandled schema: Json.Schema.DescriptionKeyword, Json.Schema.AnyOfKeyword
     */
    outputs?: any;
}

/**
 * Describes an object or resource property
 */
export interface InputPropertiesAdditionalProperties {
    additionalProperties?: {[key: string]: any};
    choice1Of5?: inputs.TypeSpecOneOf0;
    choice2Of5?: inputs.OneOf1;
    choice3Of5?: inputs.AdditionalPropertiesInputPropertiesAdditionalPropertiesChoice3Of5;
    choice4Of5?: inputs.NamedType;
    choice5Of5?: inputs.Choice5Of5;
    const?: boolean | number | string;
    default?: boolean | number | string;
    defaultInfo?: inputs.DefaultInfo;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Additional language-specific data about the property.
     */
    language?: {[key: string]: any};
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: boolean;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: boolean;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: boolean;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: boolean;
}

/**
 * Describes an object or resource property
 */
export interface InputPropertiesAdditionalPropertiesArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of5?: pulumi.Input<inputs.TypeSpecOneOf0Args>;
    choice2Of5?: pulumi.Input<inputs.OneOf1Args>;
    choice3Of5?: pulumi.Input<inputs.AdditionalPropertiesInputPropertiesAdditionalPropertiesChoice3Of5Args>;
    choice4Of5?: pulumi.Input<inputs.NamedTypeArgs>;
    choice5Of5?: pulumi.Input<inputs.Choice5Of5Args>;
    const?: pulumi.Input<boolean | number | string>;
    default?: pulumi.Input<boolean | number | string>;
    defaultInfo?: pulumi.Input<inputs.DefaultInfoArgs>;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Additional language-specific data about the property.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: pulumi.Input<boolean>;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: pulumi.Input<boolean>;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: pulumi.Input<boolean>;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: pulumi.Input<boolean>;
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface InputPropertiesAdditionalPropertiesChoice2Of5 {
    items: inputs.PropertyDefinition;
    type: "array";
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface InputPropertiesAdditionalPropertiesChoice2Of5Args {
    items: pulumi.Input<inputs.PropertyDefinitionArgs>;
    type: pulumi.Input<"array">;
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface InputPropertiesAdditionalPropertiesChoice3Of5 {
    additionalProperties?: inputs.PropertyDefinition;
    type: "object";
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface InputPropertiesAdditionalPropertiesChoice3Of5Args {
    additionalProperties?: pulumi.Input<inputs.PropertyDefinitionArgs>;
    type: pulumi.Input<"object">;
}

/**
 * Describes an object or resource property
 */
export interface InputsPropertiesAdditionalProperties {
    additionalProperties?: {[key: string]: any};
    choice1Of5?: inputs.Choice1Of5;
    choice2Of5?: inputs.TypeSpecOneOf1;
    choice3Of5?: inputs.TypeSpecOneOf2;
    choice4Of5?: inputs.NamedType;
    choice5Of5?: inputs.TypeSpecOneOf4;
    const?: boolean | number | string;
    default?: boolean | number | string;
    defaultInfo?: inputs.DefaultInfo;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Additional language-specific data about the property.
     */
    language?: {[key: string]: any};
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: boolean;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: boolean;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: boolean;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: boolean;
}

/**
 * Describes an object or resource property
 */
export interface InputsPropertiesAdditionalPropertiesArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of5?: pulumi.Input<inputs.Choice1Of5Args>;
    choice2Of5?: pulumi.Input<inputs.TypeSpecOneOf1Args>;
    choice3Of5?: pulumi.Input<inputs.TypeSpecOneOf2Args>;
    choice4Of5?: pulumi.Input<inputs.NamedTypeArgs>;
    choice5Of5?: pulumi.Input<inputs.TypeSpecOneOf4Args>;
    const?: pulumi.Input<boolean | number | string>;
    default?: pulumi.Input<boolean | number | string>;
    defaultInfo?: pulumi.Input<inputs.DefaultInfoArgs>;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Additional language-specific data about the property.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: pulumi.Input<boolean>;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: pulumi.Input<boolean>;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: pulumi.Input<boolean>;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: pulumi.Input<boolean>;
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface MapType {
    additionalProperties?: inputs.AdditionalProperties;
    type: "object";
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface MapTypeArgs {
    additionalProperties?: pulumi.Input<inputs.AdditionalPropertiesArgs>;
    type: pulumi.Input<"object">;
}

/**
 * Format metadata about this package.
 */
export interface Meta {
    /**
     * A regex that is used by the importer to extract a module name from the module portion of a type token. Packages that use the module format "namespace1/namespace2/.../namespaceN" do not need to specify a format. The regex must define one capturing group that contains the module name, which must be formatted as "namespace1/namespace2/...namespaceN".
     */
    moduleFormat?: string;
    /**
     * Write the package to support the pack command.
     */
    supportPack?: boolean;
}

/**
 * Format metadata about this package.
 */
export interface MetaArgs {
    /**
     * A regex that is used by the importer to extract a module name from the module portion of a type token. Packages that use the module format "namespace1/namespace2/.../namespaceN" do not need to specify a format. The regex must define one capturing group that contains the module name, which must be formatted as "namespace1/namespace2/...namespaceN".
     */
    moduleFormat?: pulumi.Input<string>;
    /**
     * Write the package to support the pack command.
     */
    supportPack?: pulumi.Input<boolean>;
}

/**
 * A reference to a type in this or another document. The "$ref" property must be present. The "type" property is ignored if it is present. No other properties may be present.
 */
export interface NamedType {
    /**
     * The URI of the referenced type. For example, the built-in Archive, Asset, and Any
     * types are referenced as "pulumi.json#/Archive", "pulumi.json#/Asset", and "pulumi.json#/Any", respectively.
     * A type from this document is referenced as "#/types/pulumi:type:token".
     * A type from another document is referenced as "path#/types/pulumi:type:token", where path is of the form:
     *   "/provider/vX.Y.Z/schema.json" or "pulumi.json" or "http[s]://example.com/provider/vX.Y.Z/schema.json"
     * A resource from this document is referenced as "#/resources/pulumi:type:token".
     * A resource from another document is referenced as "path#/resources/pulumi:type:token", where path is of the form:
     *   "/provider/vX.Y.Z/schema.json" or "pulumi.json" or "http[s]://example.com/provider/vX.Y.Z/schema.json"
     */
    $ref: string;
    /**
     * ignored; present for compatibility with existing schemas
     */
    type?: string;
}

/**
 * A reference to a type in this or another document. The "$ref" property must be present. The "type" property is ignored if it is present. No other properties may be present.
 */
export interface NamedTypeArgs {
    /**
     * The URI of the referenced type. For example, the built-in Archive, Asset, and Any
     * types are referenced as "pulumi.json#/Archive", "pulumi.json#/Asset", and "pulumi.json#/Any", respectively.
     * A type from this document is referenced as "#/types/pulumi:type:token".
     * A type from another document is referenced as "path#/types/pulumi:type:token", where path is of the form:
     *   "/provider/vX.Y.Z/schema.json" or "pulumi.json" or "http[s]://example.com/provider/vX.Y.Z/schema.json"
     * A resource from this document is referenced as "#/resources/pulumi:type:token".
     * A resource from another document is referenced as "path#/resources/pulumi:type:token", where path is of the form:
     *   "/provider/vX.Y.Z/schema.json" or "pulumi.json" or "http[s]://example.com/provider/vX.Y.Z/schema.json"
     */
    $ref: pulumi.Input<string>;
    /**
     * ignored; present for compatibility with existing schemas
     */
    type?: pulumi.Input<string>;
}

/**
 * Describes an object type
 */
export interface ObjectTypeDefinition {
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: {[key: string]: inputs.AdditionalProperties};
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: string[];
    type?: "object";
}

/**
 * Describes an object type
 */
export interface ObjectTypeDefinitionArgs {
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: pulumi.Input<{[key: string]: pulumi.Input<inputs.AdditionalPropertiesArgs>}>;
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: pulumi.Input<pulumi.Input<string>[]>;
    type?: pulumi.Input<"object">;
}

/**
 * Describes an object type
 */
export interface ObjectTypeDetails {
    additionalProperties?: {[key: string]: any};
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: {[key: string]: inputs.InputsPropertiesAdditionalProperties};
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: string[];
}

/**
 * Describes an object type
 */
export interface ObjectTypeDetailsArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: pulumi.Input<{[key: string]: pulumi.Input<inputs.InputsPropertiesAdditionalPropertiesArgs>}>;
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * Describes a resource or component.
 */
export interface ObjectTypeSpec {
    additionalProperties?: {[key: string]: any};
    /**
     * The list of aliases for the resource.
     */
    aliases?: inputs.AliasDefinition[];
    /**
     * Indicates whether the resource is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the resource, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * A map from property name to propertySpec that describes the resource's input properties.
     */
    inputProperties?: {[key: string]: inputs.PropertyDefinition};
    /**
     * Indicates whether the resource is a component.
     */
    isComponent?: boolean;
    /**
     * Indicates that the implementation of the resource should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: boolean;
    /**
     * A map from method name to function token that describes the resource's method set.
     */
    methods?: {[key: string]: string};
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: {[key: string]: inputs.PropertiesAdditionalProperties};
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: string[];
    /**
     * A list of the names of the resource's required input properties.
     */
    requiredInputs?: string[];
    stateInputs?: inputs.ObjectTypeSpec;
}

/**
 * Describes a resource or component.
 */
export interface ObjectTypeSpecArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * The list of aliases for the resource.
     */
    aliases?: pulumi.Input<pulumi.Input<inputs.AliasDefinitionArgs>[]>;
    /**
     * Indicates whether the resource is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the resource, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * A map from property name to propertySpec that describes the resource's input properties.
     */
    inputProperties?: pulumi.Input<{[key: string]: pulumi.Input<inputs.PropertyDefinitionArgs>}>;
    /**
     * Indicates whether the resource is a component.
     */
    isComponent?: pulumi.Input<boolean>;
    /**
     * Indicates that the implementation of the resource should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: pulumi.Input<boolean>;
    /**
     * A map from method name to function token that describes the resource's method set.
     */
    methods?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: pulumi.Input<{[key: string]: pulumi.Input<inputs.PropertiesAdditionalPropertiesArgs>}>;
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A list of the names of the resource's required input properties.
     */
    requiredInputs?: pulumi.Input<pulumi.Input<string>[]>;
    stateInputs?: pulumi.Input<inputs.ObjectTypeSpecArgs>;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface OneOf0 {
    type: enums.Type;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface OneOf0Args {
    type: pulumi.Input<enums.Type>;
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface OneOf1 {
    items: inputs.InputPropertiesAdditionalProperties;
    type: "array";
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface OneOf1Args {
    items: pulumi.Input<inputs.InputPropertiesAdditionalPropertiesArgs>;
    type: pulumi.Input<"array">;
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface OneOf2 {
    additionalProperties?: inputs.PropertiesAdditionalProperties;
    type: "object";
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface OneOf2Args {
    additionalProperties?: pulumi.Input<inputs.PropertiesAdditionalPropertiesArgs>;
    type: pulumi.Input<"object">;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface OneOf4 {
    discriminator?: inputs.Discriminator;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: inputs.VariablesAdditionalProperties[];
    type?: enums.VariablesAdditionalPropertiesChoice5Of5Type;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface OneOf4Args {
    discriminator?: pulumi.Input<inputs.DiscriminatorArgs>;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: pulumi.Input<pulumi.Input<inputs.VariablesAdditionalPropertiesArgs>[]>;
    type?: pulumi.Input<enums.VariablesAdditionalPropertiesChoice5Of5Type>;
}

/**
 * An optional object to define parameterization for the package.
 */
export interface Parameterization {
    baseProvider?: inputs.BaseProvider;
    /**
     * The parameter for the provider.
     */
    parameter?: string;
}

/**
 * An optional object to define parameterization for the package.
 */
export interface ParameterizationArgs {
    baseProvider?: pulumi.Input<inputs.BaseProviderArgs>;
    /**
     * The parameter for the provider.
     */
    parameter?: pulumi.Input<string>;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface PrimitiveType {
    type: enums.OneOf0PropertiesType;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface PrimitiveTypeArgs {
    type: pulumi.Input<enums.OneOf0PropertiesType>;
}

/**
 * Describes an object or resource property
 */
export interface PropertiesAdditionalProperties {
    additionalProperties?: {[key: string]: any};
    choice1Of5?: inputs.PropertiesAdditionalPropertiesChoice1Of5;
    choice2Of5?: inputs.PropertiesAdditionalPropertiesChoice2Of5;
    choice3Of5?: inputs.OneOf2;
    choice4Of5?: inputs.NamedType;
    choice5Of5?: inputs.ProviderPropertiesAdditionalPropertiesChoice5Of5;
    const?: boolean | number | string;
    default?: boolean | number | string;
    defaultInfo?: inputs.DefaultInfo;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Additional language-specific data about the property.
     */
    language?: {[key: string]: any};
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: boolean;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: boolean;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: boolean;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: boolean;
}

/**
 * Describes an object or resource property
 */
export interface PropertiesAdditionalPropertiesArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of5?: pulumi.Input<inputs.PropertiesAdditionalPropertiesChoice1Of5Args>;
    choice2Of5?: pulumi.Input<inputs.PropertiesAdditionalPropertiesChoice2Of5Args>;
    choice3Of5?: pulumi.Input<inputs.OneOf2Args>;
    choice4Of5?: pulumi.Input<inputs.NamedTypeArgs>;
    choice5Of5?: pulumi.Input<inputs.ProviderPropertiesAdditionalPropertiesChoice5Of5Args>;
    const?: pulumi.Input<boolean | number | string>;
    default?: pulumi.Input<boolean | number | string>;
    defaultInfo?: pulumi.Input<inputs.DefaultInfoArgs>;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Additional language-specific data about the property.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: pulumi.Input<boolean>;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: pulumi.Input<boolean>;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: pulumi.Input<boolean>;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: pulumi.Input<boolean>;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface PropertiesAdditionalPropertiesChoice1Of5 {
    type: enums.PropertiesAdditionalPropertiesChoice1Of5Type;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface PropertiesAdditionalPropertiesChoice1Of5Args {
    type: pulumi.Input<enums.PropertiesAdditionalPropertiesChoice1Of5Type>;
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface PropertiesAdditionalPropertiesChoice2Of5 {
    items: inputs.PropertiesAdditionalProperties;
    type: "array";
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface PropertiesAdditionalPropertiesChoice2Of5Args {
    items: pulumi.Input<inputs.PropertiesAdditionalPropertiesArgs>;
    type: pulumi.Input<"array">;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface PropertiesAdditionalPropertiesChoice5Of5 {
    discriminator?: inputs.Discriminator;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: inputs.AdditionalProperties[];
    type?: enums.AdditionalPropertiesChoice5Of5Type;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface PropertiesAdditionalPropertiesChoice5Of5Args {
    discriminator?: pulumi.Input<inputs.DiscriminatorArgs>;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: pulumi.Input<pulumi.Input<inputs.AdditionalPropertiesArgs>[]>;
    type?: pulumi.Input<enums.AdditionalPropertiesChoice5Of5Type>;
}

/**
 * Describes an object or resource property
 */
export interface PropertyDefinition {
    additionalProperties?: {[key: string]: any};
    choice1Of5?: inputs.AdditionalPropertiesChoice1Of5;
    choice2Of5?: inputs.InputPropertiesAdditionalPropertiesChoice2Of5;
    choice3Of5?: inputs.InputPropertiesAdditionalPropertiesChoice3Of5;
    choice4Of5?: inputs.NamedType;
    choice5Of5?: inputs.UnionType;
    const?: boolean | number | string;
    default?: boolean | number | string;
    defaultInfo?: inputs.DefaultInfo;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Additional language-specific data about the property.
     */
    language?: {[key: string]: any};
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: boolean;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: boolean;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: boolean;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: boolean;
}

/**
 * Describes an object or resource property
 */
export interface PropertyDefinitionArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of5?: pulumi.Input<inputs.AdditionalPropertiesChoice1Of5Args>;
    choice2Of5?: pulumi.Input<inputs.InputPropertiesAdditionalPropertiesChoice2Of5Args>;
    choice3Of5?: pulumi.Input<inputs.InputPropertiesAdditionalPropertiesChoice3Of5Args>;
    choice4Of5?: pulumi.Input<inputs.NamedTypeArgs>;
    choice5Of5?: pulumi.Input<inputs.UnionTypeArgs>;
    const?: pulumi.Input<boolean | number | string>;
    default?: pulumi.Input<boolean | number | string>;
    defaultInfo?: pulumi.Input<inputs.DefaultInfoArgs>;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Additional language-specific data about the property.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: pulumi.Input<boolean>;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: pulumi.Input<boolean>;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: pulumi.Input<boolean>;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: pulumi.Input<boolean>;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface ProviderPropertiesAdditionalPropertiesChoice5Of5 {
    discriminator?: inputs.Discriminator;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: inputs.PropertiesAdditionalProperties[];
    type?: enums.TypeSpecOneOf4PropertiesType;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface ProviderPropertiesAdditionalPropertiesChoice5Of5Args {
    discriminator?: pulumi.Input<inputs.DiscriminatorArgs>;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: pulumi.Input<pulumi.Input<inputs.PropertiesAdditionalPropertiesArgs>[]>;
    type?: pulumi.Input<enums.TypeSpecOneOf4PropertiesType>;
}

/**
 * A description of the schema for a Pulumi Package
 */
export interface PulumiPackageMetaschema {
    /**
     * Freeform text attribution of derived work, if required.
     */
    attribution?: string;
    config?: inputs.Config;
    /**
     * The description of the package. Descriptions are interpreted as Markdown.
     */
    description?: string;
    /**
     * The human-friendly name of the package.
     */
    displayName?: string;
    /**
     * A map from token to functionSpec that describes the set of functions defined by this package.
     */
    functions?: {[key: string]: inputs.FunctionDefinition};
    /**
     * The package's homepage.
     */
    homepage?: string;
    /**
     * The list of keywords that are associated with the package, if any.
     */
    keywords?: string[];
    /**
     * Additional language-specific data about the package.
     */
    language?: {[key: string]: any};
    /**
     * The name of the license used for the package's contents.
     */
    license?: string;
    /**
     * The URL of the package's logo, if any.
     */
    logoUrl?: string;
    meta?: inputs.Meta;
    /**
     * The unqualified name of the package (e.g. "aws", "azure", "gcp", "kubernetes", "random")
     */
    name: string;
    parameterization?: inputs.Parameterization;
    /**
     * The URL to use when downloading the provider plugin binary.
     */
    pluginDownloadURL?: string;
    provider?: inputs.ObjectTypeSpec;
    /**
     * The name of the person or organization that authored and published the package.
     */
    publisher?: string;
    /**
     * The URL at which the package's sources can be found.
     */
    repository?: string;
    /**
     * A map from type token to resourceSpec that describes the set of resources and components defined by this package.
     */
    resources?: {[key: string]: inputs.ResourceDefinition};
    /**
     * A map from type token to complexTypeSpec that describes the set of complex types (i.e. object, enum) defined by this package.
     */
    types?: {[key: string]: inputs.TypeDefinition};
    /**
     * The version of the package. The version must be valid semver.
     */
    version?: string;
}

/**
 * A description of the schema for a Pulumi Package
 */
export interface PulumiPackageMetaschemaArgs {
    /**
     * Freeform text attribution of derived work, if required.
     */
    attribution?: pulumi.Input<string>;
    config?: pulumi.Input<inputs.ConfigArgs>;
    /**
     * The description of the package. Descriptions are interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * The human-friendly name of the package.
     */
    displayName?: pulumi.Input<string>;
    /**
     * A map from token to functionSpec that describes the set of functions defined by this package.
     */
    functions?: pulumi.Input<{[key: string]: pulumi.Input<inputs.FunctionDefinitionArgs>}>;
    /**
     * The package's homepage.
     */
    homepage?: pulumi.Input<string>;
    /**
     * The list of keywords that are associated with the package, if any.
     */
    keywords?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Additional language-specific data about the package.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * The name of the license used for the package's contents.
     */
    license?: pulumi.Input<string>;
    /**
     * The URL of the package's logo, if any.
     */
    logoUrl?: pulumi.Input<string>;
    meta?: pulumi.Input<inputs.MetaArgs>;
    /**
     * The unqualified name of the package (e.g. "aws", "azure", "gcp", "kubernetes", "random")
     */
    name: pulumi.Input<string>;
    parameterization?: pulumi.Input<inputs.ParameterizationArgs>;
    /**
     * The URL to use when downloading the provider plugin binary.
     */
    pluginDownloadURL?: pulumi.Input<string>;
    provider?: pulumi.Input<inputs.ObjectTypeSpecArgs>;
    /**
     * The name of the person or organization that authored and published the package.
     */
    publisher?: pulumi.Input<string>;
    /**
     * The URL at which the package's sources can be found.
     */
    repository?: pulumi.Input<string>;
    /**
     * A map from type token to resourceSpec that describes the set of resources and components defined by this package.
     */
    resources?: pulumi.Input<{[key: string]: pulumi.Input<inputs.ResourceDefinitionArgs>}>;
    /**
     * A map from type token to complexTypeSpec that describes the set of complex types (i.e. object, enum) defined by this package.
     */
    types?: pulumi.Input<{[key: string]: pulumi.Input<inputs.TypeDefinitionArgs>}>;
    /**
     * The version of the package. The version must be valid semver.
     */
    version?: pulumi.Input<string>;
}

/**
 * Describes a resource or component.
 */
export interface ResourceDefinition {
    additionalProperties?: {[key: string]: any};
    /**
     * The list of aliases for the resource.
     */
    aliases?: inputs.AliasDefinition[];
    /**
     * Indicates whether the resource is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the resource, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * A map from property name to propertySpec that describes the resource's input properties.
     */
    inputProperties?: {[key: string]: inputs.InputPropertiesAdditionalProperties};
    /**
     * Indicates whether the resource is a component.
     */
    isComponent?: boolean;
    /**
     * Indicates that the implementation of the resource should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: boolean;
    /**
     * A map from method name to function token that describes the resource's method set.
     */
    methods?: {[key: string]: string};
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: {[key: string]: inputs.TypeSpec};
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: string[];
    /**
     * A list of the names of the resource's required input properties.
     */
    requiredInputs?: string[];
    stateInputs?: inputs.ResourceDefinition;
}

/**
 * Describes a resource or component.
 */
export interface ResourceDefinitionArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    /**
     * The list of aliases for the resource.
     */
    aliases?: pulumi.Input<pulumi.Input<inputs.AliasDefinitionArgs>[]>;
    /**
     * Indicates whether the resource is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the resource, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * A map from property name to propertySpec that describes the resource's input properties.
     */
    inputProperties?: pulumi.Input<{[key: string]: pulumi.Input<inputs.InputPropertiesAdditionalPropertiesArgs>}>;
    /**
     * Indicates whether the resource is a component.
     */
    isComponent?: pulumi.Input<boolean>;
    /**
     * Indicates that the implementation of the resource should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: pulumi.Input<boolean>;
    /**
     * A map from method name to function token that describes the resource's method set.
     */
    methods?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * A map from property name to propertySpec that describes the object's properties.
     */
    properties?: pulumi.Input<{[key: string]: pulumi.Input<inputs.TypeSpecArgs>}>;
    /**
     * A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
     */
    required?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A list of the names of the resource's required input properties.
     */
    requiredInputs?: pulumi.Input<pulumi.Input<string>[]>;
    stateInputs?: pulumi.Input<inputs.ResourceDefinitionArgs>;
}

/**
 * Describes an object or enum type.
 */
export interface TypeDefinition {
    additionalProperties?: {[key: string]: any};
    choice1Of2?: inputs.ObjectTypeDefinition;
    choice2Of2?: inputs.EnumTypeDefinition;
    /**
     * The description of the type, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Indicates that the implementation of the type should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: boolean;
    /**
     * Additional language-specific data about the type.
     */
    language?: {[key: string]: any};
}

/**
 * Describes an object or enum type.
 */
export interface TypeDefinitionArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of2?: pulumi.Input<inputs.ObjectTypeDefinitionArgs>;
    choice2Of2?: pulumi.Input<inputs.EnumTypeDefinitionArgs>;
    /**
     * The description of the type, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Indicates that the implementation of the type should not be generated from the schema, and is instead provided out-of-band by the package author
     */
    isOverlay?: pulumi.Input<boolean>;
    /**
     * Additional language-specific data about the type.
     */
    language?: pulumi.Input<{[key: string]: any}>;
}

/**
 * Describes an object or resource property
 */
export interface TypeSpec {
    additionalProperties?: {[key: string]: any};
    choice1Of5?: inputs.OneOf0;
    choice2Of5?: inputs.AdditionalPropertiesChoice2Of5;
    choice3Of5?: inputs.AdditionalPropertiesChoice3Of5;
    choice4Of5?: inputs.NamedType;
    choice5Of5?: inputs.AdditionalPropertiesChoice5Of5;
    const?: boolean | number | string;
    default?: boolean | number | string;
    defaultInfo?: inputs.DefaultInfo;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Additional language-specific data about the property.
     */
    language?: {[key: string]: any};
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: boolean;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: boolean;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: boolean;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: boolean;
}

/**
 * Describes an object or resource property
 */
export interface TypeSpecArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of5?: pulumi.Input<inputs.OneOf0Args>;
    choice2Of5?: pulumi.Input<inputs.AdditionalPropertiesChoice2Of5Args>;
    choice3Of5?: pulumi.Input<inputs.AdditionalPropertiesChoice3Of5Args>;
    choice4Of5?: pulumi.Input<inputs.NamedTypeArgs>;
    choice5Of5?: pulumi.Input<inputs.AdditionalPropertiesChoice5Of5Args>;
    const?: pulumi.Input<boolean | number | string>;
    default?: pulumi.Input<boolean | number | string>;
    defaultInfo?: pulumi.Input<inputs.DefaultInfoArgs>;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Additional language-specific data about the property.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: pulumi.Input<boolean>;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: pulumi.Input<boolean>;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: pulumi.Input<boolean>;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: pulumi.Input<boolean>;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface TypeSpecOneOf0 {
    type: enums.TypeSpecOneOf0PropertiesType;
}

/**
 * A reference to a primitive type. A primitive type must have only the "type" property set.
 */
export interface TypeSpecOneOf0Args {
    type: pulumi.Input<enums.TypeSpecOneOf0PropertiesType>;
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface TypeSpecOneOf1 {
    items: inputs.InputsPropertiesAdditionalProperties;
    type: "array";
}

/**
 * A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
 */
export interface TypeSpecOneOf1Args {
    items: pulumi.Input<inputs.InputsPropertiesAdditionalPropertiesArgs>;
    type: pulumi.Input<"array">;
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface TypeSpecOneOf2 {
    additionalProperties?: inputs.InputsPropertiesAdditionalProperties;
    type: "object";
}

/**
 * A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
 */
export interface TypeSpecOneOf2Args {
    additionalProperties?: pulumi.Input<inputs.InputsPropertiesAdditionalPropertiesArgs>;
    type: pulumi.Input<"object">;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface TypeSpecOneOf4 {
    discriminator?: inputs.Discriminator;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: inputs.InputsPropertiesAdditionalProperties[];
    type?: enums.PropertiesAdditionalPropertiesChoice5Of5Type;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface TypeSpecOneOf4Args {
    discriminator?: pulumi.Input<inputs.DiscriminatorArgs>;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: pulumi.Input<pulumi.Input<inputs.InputsPropertiesAdditionalPropertiesArgs>[]>;
    type?: pulumi.Input<enums.PropertiesAdditionalPropertiesChoice5Of5Type>;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface UnionType {
    discriminator?: inputs.Discriminator;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: inputs.PropertyDefinition[];
    type?: enums.Choice5Of5Type;
}

/**
 * A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
 */
export interface UnionTypeArgs {
    discriminator?: pulumi.Input<inputs.DiscriminatorArgs>;
    /**
     * If present, indicates that values of the type may be one of any of the listed types
     */
    oneOf: pulumi.Input<pulumi.Input<inputs.PropertyDefinitionArgs>[]>;
    type?: pulumi.Input<enums.Choice5Of5Type>;
}

/**
 * Describes an object or resource property
 */
export interface VariablesAdditionalProperties {
    additionalProperties?: {[key: string]: any};
    choice1Of5?: inputs.PrimitiveType;
    choice2Of5?: inputs.ArrayType;
    choice3Of5?: inputs.Choice3Of5;
    choice4Of5?: inputs.NamedType;
    choice5Of5?: inputs.OneOf4;
    const?: boolean | number | string;
    default?: boolean | number | string;
    defaultInfo?: inputs.DefaultInfo;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: string;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: string;
    /**
     * Additional language-specific data about the property.
     */
    language?: {[key: string]: any};
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: boolean;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: boolean;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: boolean;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: boolean;
}

/**
 * Describes an object or resource property
 */
export interface VariablesAdditionalPropertiesArgs {
    additionalProperties?: pulumi.Input<{[key: string]: any}>;
    choice1Of5?: pulumi.Input<inputs.PrimitiveTypeArgs>;
    choice2Of5?: pulumi.Input<inputs.ArrayTypeArgs>;
    choice3Of5?: pulumi.Input<inputs.Choice3Of5Args>;
    choice4Of5?: pulumi.Input<inputs.NamedTypeArgs>;
    choice5Of5?: pulumi.Input<inputs.OneOf4Args>;
    const?: pulumi.Input<boolean | number | string>;
    default?: pulumi.Input<boolean | number | string>;
    defaultInfo?: pulumi.Input<inputs.DefaultInfoArgs>;
    /**
     * Indicates whether the property is deprecated
     */
    deprecationMessage?: pulumi.Input<string>;
    /**
     * The description of the property, if any. Interpreted as Markdown.
     */
    description?: pulumi.Input<string>;
    /**
     * Additional language-specific data about the property.
     */
    language?: pulumi.Input<{[key: string]: any}>;
    /**
     * Indicates that when used as an input, this type does not accept eventual values.
     */
    plain?: pulumi.Input<boolean>;
    /**
     * Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
     */
    replaceOnChanges?: pulumi.Input<boolean>;
    /**
     * Specifies whether the property is secret (default false).
     */
    secret?: pulumi.Input<boolean>;
    /**
     * Indicates that the provider will replace the resource when this property is changed.
     */
    willReplaceOnChanges?: pulumi.Input<boolean>;
}
