// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Outputs
{

    [OutputType]
    public sealed class BaseProvider
    {
        /// <summary>
        /// The unqualified name of the package (e.g. "aws", "azure", "gcp", "kubernetes", "random")
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The URL to use when downloading the provider plugin binary.
        /// </summary>
        public readonly string? PluginDownloadURL;
        /// <summary>
        /// The version of the package. The version must be valid semver.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private BaseProvider(
            string name,

            string? pluginDownloadURL,

            string version)
        {
            Name = name;
            PluginDownloadURL = pluginDownloadURL;
            Version = version;
        }
    }
}
