// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Outputs
{

    [OutputType]
    public sealed class EnumValueDefinition
    {
        public readonly ImmutableDictionary<string, object>? AdditionalProperties;
        /// <summary>
        /// Indicates whether the value is deprecated.
        /// </summary>
        public readonly string? DeprecationMessage;
        /// <summary>
        /// The description of the enum value, if any. Interpreted as Markdown.
        /// </summary>
        public readonly string? Description;
        /// <summary>
        /// If present, overrides the name of the enum value that would usually be derived from the value.
        /// </summary>
        public readonly string? Name;
        public readonly object Value;

        [OutputConstructor]
        private EnumValueDefinition(
            ImmutableDictionary<string, object>? additionalProperties,

            string? deprecationMessage,

            string? description,

            string? name,

            object value)
        {
            AdditionalProperties = additionalProperties;
            DeprecationMessage = deprecationMessage;
            Description = description;
            Name = name;
            Value = value;
        }
    }
}
