// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Outputs
{

    /// <summary>
    /// An optional object to define parameterization for the package.
    /// </summary>
    [OutputType]
    public sealed class Parameterization
    {
        public readonly Outputs.BaseProvider? BaseProvider;
        /// <summary>
        /// The parameter for the provider.
        /// </summary>
        public readonly string? Parameter;

        [OutputConstructor]
        private Parameterization(
            Outputs.BaseProvider? baseProvider,

            string? parameter)
        {
            BaseProvider = baseProvider;
            Parameter = parameter;
        }
    }
}
