// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Outputs
{

    /// <summary>
    /// Describes an enum type
    /// </summary>
    [OutputType]
    public sealed class EnumTypeDefinition
    {
        /// <summary>
        /// The list of possible values for the enum
        /// </summary>
        public readonly ImmutableArray<Outputs.EnumValueDefinition> Enum;
        public readonly Pulumi.Pulumi.EnumTypeSpecType Type;

        [OutputConstructor]
        private EnumTypeDefinition(
            ImmutableArray<Outputs.EnumValueDefinition> @enum,

            Pulumi.Pulumi.EnumTypeSpecType type)
        {
            Enum = @enum;
            Type = type;
        }
    }
}
