// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Outputs
{

    /// <summary>
    /// Informs the consumer of an alternative schema based on the value associated with it
    /// </summary>
    [OutputType]
    public sealed class PropertySpecOneOf4Discriminator6
    {
        public readonly ImmutableDictionary<string, object>? AdditionalProperties;
        /// <summary>
        /// an optional object to hold mappings between payload values and schema names or references
        /// </summary>
        public readonly ImmutableDictionary<string, string>? Mapping;
        /// <summary>
        /// PropertyName is the name of the property in the payload that will hold the discriminator value
        /// </summary>
        public readonly string PropertyName;

        [OutputConstructor]
        private PropertySpecOneOf4Discriminator6(
            ImmutableDictionary<string, object>? additionalProperties,

            ImmutableDictionary<string, string>? mapping,

            string propertyName)
        {
            AdditionalProperties = additionalProperties;
            Mapping = mapping;
            PropertyName = propertyName;
        }
    }
}
