// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    public sealed class AliasDefinitionArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalProperties")]
        private Dictionary<string, object>? _additionalProperties;
        public Dictionary<string, object> AdditionalProperties
        {
            get => _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>());
            set => _additionalProperties = value;
        }

        /// <summary>
        /// The name portion of the alias, if any
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The project portion of the alias, if any
        /// </summary>
        [Input("project")]
        public string? Project { get; set; }

        /// <summary>
        /// The type portion of the alias, if any
        /// </summary>
        [Input("type")]
        public string? Type { get; set; }

        public AliasDefinitionArgs()
        {
        }
        public static new AliasDefinitionArgs Empty => new AliasDefinitionArgs();
    }
}
