// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// A reference to a primitive type. A primitive type must have only the "type" property set.
    /// </summary>
    public sealed class Choice1Of5Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The primitive type, if any
        /// </summary>
        [Input("type", required: true)]
        public Input<Pulumi.Pulumi.TypeSpecOneOf0PropertiesType> Type { get; set; } = null!;

        public Choice1Of5Args()
        {
        }
        public static new Choice1Of5Args Empty => new Choice1Of5Args();
    }
}
