// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// The package's configuration variables.
    /// </summary>
    public sealed class ConfigArgs : global::Pulumi.ResourceArgs
    {
        [Input("defaults")]
        private List<string>? _defaults;

        /// <summary>
        /// A list of the names of the package's non-required configuration variables.
        /// </summary>
        public List<string> Defaults
        {
            get => _defaults ?? (_defaults = new List<string>());
            set => _defaults = value;
        }

        [Input("variables")]
        private Dictionary<string, Inputs.VariablesAdditionalPropertiesArgs>? _variables;

        /// <summary>
        /// A map from variable name to propertySpec that describes a package's configuration variables.
        /// </summary>
        public Dictionary<string, Inputs.VariablesAdditionalPropertiesArgs> Variables
        {
            get => _variables ?? (_variables = new Dictionary<string, Inputs.VariablesAdditionalPropertiesArgs>());
            set => _variables = value;
        }

        public ConfigArgs()
        {
        }
        public static new ConfigArgs Empty => new ConfigArgs();
    }
}
