// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// Describes an enum type
    /// </summary>
    public sealed class EnumTypeDefinitionArgs : global::Pulumi.ResourceArgs
    {
        [Input("enum", required: true)]
        private List<Inputs.EnumValueDefinitionArgs>? _enum;

        /// <summary>
        /// The list of possible values for the enum
        /// </summary>
        public List<Inputs.EnumValueDefinitionArgs> Enum
        {
            get => _enum ?? (_enum = new List<Inputs.EnumValueDefinitionArgs>());
            set => _enum = value;
        }

        [Input("type", required: true)]
        public Pulumi.Pulumi.EnumTypeSpecPropertiesType Type { get; set; }

        public EnumTypeDefinitionArgs()
        {
        }
        public static new EnumTypeDefinitionArgs Empty => new EnumTypeDefinitionArgs();
    }
}
