// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// A reference to a primitive type. A primitive type must have only the "type" property set.
    /// </summary>
    public sealed class OneOf0Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The primitive type, if any
        /// </summary>
        [Input("type", required: true)]
        public Input<Pulumi.Pulumi.PropertiesType> Type { get; set; } = null!;

        public OneOf0Args()
        {
        }
        public static new OneOf0Args Empty => new OneOf0Args();
    }
}
