// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// Describes an object or resource property
    /// </summary>
    public sealed class PropertiesAdditionalProperties : global::Pulumi.InvokeArgs
    {
        [Input("additionalProperties")]
        private Dictionary<string, object>? _additionalProperties;
        public Dictionary<string, object> AdditionalProperties
        {
            get => _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>());
            set => _additionalProperties = value;
        }

        /// <summary>
        /// A reference to a primitive type. A primitive type must have only the "type" property set.
        /// </summary>
        [Input("choice1Of5")]
        public Inputs.Choice1Of5? Choice1Of5 { get; set; }

        /// <summary>
        /// A reference to an array type. The "type" property must be set to "array" and the "items" property must be present. No other properties may be present.
        /// </summary>
        [Input("choice2Of5")]
        public Inputs.Choice2Of5? Choice2Of5 { get; set; }

        /// <summary>
        /// A reference to a map type. The "type" property must be set to "object" and the "additionalProperties" property may be present. No other properties may be present.
        /// </summary>
        [Input("choice3Of5")]
        public Inputs.Choice3Of5? Choice3Of5 { get; set; }

        /// <summary>
        /// A reference to a type in this or another document. The "$ref" property must be present. The "type" property is ignored if it is present. No other properties may be present.
        /// </summary>
        [Input("choice4Of5")]
        public Inputs.NamedType? Choice4Of5 { get; set; }

        /// <summary>
        /// A reference to a union type. The "oneOf" property must be present. The union may additional specify an underlying primitive type via the "type" property and a discriminator via the "discriminator" property. No other properties may be present.
        /// </summary>
        [Input("choice5Of5")]
        public Inputs.Choice5Of5? Choice5Of5 { get; set; }

        [Input("const")]
        public object? Const { get; set; }

        [Input("default")]
        public object? Default { get; set; }

        /// <summary>
        /// Additional information about the property's default value, if any.
        /// </summary>
        [Input("defaultInfo")]
        public Inputs.DefaultInfo? DefaultInfo { get; set; }

        /// <summary>
        /// Indicates whether the property is deprecated
        /// </summary>
        [Input("deprecationMessage")]
        public string? DeprecationMessage { get; set; }

        /// <summary>
        /// The description of the property, if any. Interpreted as Markdown.
        /// </summary>
        [Input("description")]
        public string? Description { get; set; }

        [Input("language")]
        private Dictionary<string, object>? _language;

        /// <summary>
        /// Additional language-specific data about the property.
        /// </summary>
        public Dictionary<string, object> Language
        {
            get => _language ?? (_language = new Dictionary<string, object>());
            set => _language = value;
        }

        /// <summary>
        /// Indicates that when used as an input, this type does not accept eventual values.
        /// </summary>
        [Input("plain")]
        public bool? Plain { get; set; }

        /// <summary>
        /// Specifies whether a change to the property causes its containing resource to be replaced instead of updated (default false).
        /// </summary>
        [Input("replaceOnChanges")]
        public bool? ReplaceOnChanges { get; set; }

        /// <summary>
        /// Specifies whether the property is secret (default false).
        /// </summary>
        [Input("secret")]
        public bool? Secret { get; set; }

        /// <summary>
        /// Indicates that the provider will replace the resource when this property is changed.
        /// </summary>
        [Input("willReplaceOnChanges")]
        public bool? WillReplaceOnChanges { get; set; }

        public PropertiesAdditionalProperties()
        {
        }
        public static new PropertiesAdditionalProperties Empty => new PropertiesAdditionalProperties();
    }
}
