// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// Additional information about the property's default value, if any.
    /// </summary>
    public sealed class ConfigVariablesAdditionalPropertiesDefaultInfoArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalProperties")]
        private InputMap<object>? _additionalProperties;
        public InputMap<object> AdditionalProperties
        {
            get => _additionalProperties ?? (_additionalProperties = new InputMap<object>());
            set => _additionalProperties = value;
        }

        [Input("environment", required: true)]
        private InputList<string>? _environment;

        /// <summary>
        /// A set of environment variables to probe for a default value.
        /// </summary>
        public InputList<string> Environment
        {
            get => _environment ?? (_environment = new InputList<string>());
            set => _environment = value;
        }

        [Input("language")]
        private InputMap<object>? _language;

        /// <summary>
        /// Additional language-specific data about the default value.
        /// </summary>
        public InputMap<object> Language
        {
            get => _language ?? (_language = new InputMap<object>());
            set => _language = value;
        }

        public ConfigVariablesAdditionalPropertiesDefaultInfoArgs()
        {
        }
        public static new ConfigVariablesAdditionalPropertiesDefaultInfoArgs Empty => new ConfigVariablesAdditionalPropertiesDefaultInfoArgs();
    }
}
