// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    public sealed class EnumValueDefinition : global::Pulumi.InvokeArgs
    {
        [Input("additionalProperties")]
        private Dictionary<string, object>? _additionalProperties;
        public Dictionary<string, object> AdditionalProperties
        {
            get => _additionalProperties ?? (_additionalProperties = new Dictionary<string, object>());
            set => _additionalProperties = value;
        }

        /// <summary>
        /// Indicates whether the value is deprecated.
        /// </summary>
        [Input("deprecationMessage")]
        public string? DeprecationMessage { get; set; }

        /// <summary>
        /// The description of the enum value, if any. Interpreted as Markdown.
        /// </summary>
        [Input("description")]
        public string? Description { get; set; }

        /// <summary>
        /// If present, overrides the name of the enum value that would usually be derived from the value.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The enum value itself
        /// </summary>
        [Input("value", required: true)]
        public object Value { get; set; } = null!;

        public EnumValueDefinition()
        {
        }
        public static new EnumValueDefinition Empty => new EnumValueDefinition();
    }
}
