// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Pulumi.Inputs
{

    /// <summary>
    /// Describes an object type
    /// </summary>
    public sealed class ObjectTypeDefinitionArgs : global::Pulumi.ResourceArgs
    {
        [Input("properties")]
        private InputMap<Inputs.PropertyDefinition2Args>? _properties;

        /// <summary>
        /// A map from property name to propertySpec that describes the object's properties.
        /// </summary>
        public InputMap<Inputs.PropertyDefinition2Args> Properties
        {
            get => _properties ?? (_properties = new InputMap<Inputs.PropertyDefinition2Args>());
            set => _properties = value;
        }

        [Input("required")]
        private InputList<string>? _required;

        /// <summary>
        /// A list of the names of an object type's required properties. These properties must be set for inputs and will always be set for outputs.
        /// </summary>
        public InputList<string> Required
        {
            get => _required ?? (_required = new InputList<string>());
            set => _required = value;
        }

        [Input("type")]
        public Input<string>? Type { get; set; }

        public ObjectTypeDefinitionArgs()
        {
        }
        public static new ObjectTypeDefinitionArgs Empty => new ObjectTypeDefinitionArgs();
    }
}
