// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GithubWorkflow.Outputs
{

    [OutputType]
    public sealed class A0
    {
        /// <summary>
        /// default any for anyOf
        /// </summary>
        public readonly object? Concurrency;
        public readonly Outputs.A3? Defaults;
        /// <summary>
        /// default any for anyOf
        /// </summary>
        public readonly object? Env;
        public readonly Outputs.A2 Jobs;
        /// <summary>
        /// The name of your workflow. GitHub displays the names of your workflows on your repository's actions page. If you omit this field, GitHub sets the name to the workflow's filename.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// default any for anyOf
        /// </summary>
        public readonly object On;
        /// <summary>
        /// default any for anyOf
        /// </summary>
        public readonly object? Permissions;
        /// <summary>
        /// The name for workflow runs generated from the workflow. GitHub displays the workflow run name in the list of workflow runs on your repository's 'Actions' tab.
        /// </summary>
        public readonly string? Run-name;

        [OutputConstructor]
        private A0(
            object? concurrency,

            Outputs.A3? defaults,

            object? env,

            Outputs.A2 jobs,

            string? name,

            object on,

            object? permissions,

            string? run-name)
        {
            Concurrency = concurrency;
            Defaults = defaults;
            Env = env;
            Jobs = jobs;
            Name = name;
            On = on;
            Permissions = permissions;
            Run-name = run-name;
        }
    }
}
