// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GithubWorkflow.Outputs
{

    [OutputType]
    public sealed class Definitions_defaults_run
    {
        /// <summary>
        /// unhandled schema: Json.Schema.CommentKeyword, Json.Schema.DescriptionKeyword, Json.Schema.AnyOfKeyword
        /// </summary>
        public readonly object? Shell;
        /// <summary>
        /// Using the working-directory keyword, you can specify the working directory of where to run the command.
        /// </summary>
        public readonly string? Working-directory;

        [OutputConstructor]
        private Definitions_defaults_run(
            object? shell,

            string? working-directory)
        {
            Shell = shell;
            Working-directory = working-directory;
        }
    }
}
