// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Cargo.Outputs
{

    /// <summary>
    /// Options for assets paths resolution and how to build assets collection
    /// </summary>
    [OutputType]
    public sealed class AssetsConfiguration
    {
        /// <summary>
        /// Allow build assets for dependencies.
        /// </summary>
        public readonly bool? Dependencies;
        public readonly bool? FollowSymlinks;
        public readonly Pulumi.Cargo.Method? Method;
        /// <summary>
        /// Allow overwriting existing files.
        /// </summary>
        public readonly bool? Overwrite;

        [OutputConstructor]
        private AssetsConfiguration(
            bool? dependencies,

            bool? followSymlinks,

            Pulumi.Cargo.Method? method,

            bool? overwrite)
        {
            Dependencies = dependencies;
            FollowSymlinks = followSymlinks;
            Method = method;
            Overwrite = overwrite;
        }
    }
}
