// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Jsonschema.Inputs
{

    public sealed class RootArgs : global::Pulumi.ResourceArgs
    {
        [Input("attribution")]
        public Input<string>? Attribution { get; set; }

        [Input("config")]
        private InputMap<string>? _config;
        public InputMap<string> Config
        {
            get => _config ?? (_config = new InputMap<string>());
            set => _config = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("displayName")]
        public Input<string>? DisplayName { get; set; }

        [Input("functions")]
        private InputMap<ImmutableDictionary<string, string>>? _functions;
        public InputMap<ImmutableDictionary<string, string>> Functions
        {
            get => _functions ?? (_functions = new InputMap<ImmutableDictionary<string, string>>());
            set => _functions = value;
        }

        [Input("homepage")]
        public Input<string>? Homepage { get; set; }

        [Input("keywords")]
        private InputList<string>? _keywords;
        public InputList<string> Keywords
        {
            get => _keywords ?? (_keywords = new InputList<string>());
            set => _keywords = value;
        }

        [Input("language")]
        private InputMap<object>? _language;
        public InputMap<object> Language
        {
            get => _language ?? (_language = new InputMap<object>());
            set => _language = value;
        }

        [Input("license")]
        public Input<string>? License { get; set; }

        [Input("logoUrl")]
        public Input<string>? LogoUrl { get; set; }

        [Input("meta")]
        private InputMap<string>? _meta;
        public InputMap<string> Meta
        {
            get => _meta ?? (_meta = new InputMap<string>());
            set => _meta = value;
        }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("pluginDownloadURL")]
        public Input<string>? PluginDownloadURL { get; set; }

        [Input("provider")]
        public Input<object>? Provider { get; set; }

        [Input("publisher")]
        public Input<string>? Publisher { get; set; }

        [Input("repository")]
        public Input<string>? Repository { get; set; }

        [Input("resources")]
        private InputMap<object>? _resources;
        public InputMap<object> Resources
        {
            get => _resources ?? (_resources = new InputMap<object>());
            set => _resources = value;
        }

        [Input("types")]
        private InputMap<object>? _types;
        public InputMap<object> Types
        {
            get => _types ?? (_types = new InputMap<object>());
            set => _types = value;
        }

        [Input("version")]
        public Input<string>? Version { get; set; }

        public RootArgs()
        {
        }
        public static new RootArgs Empty => new RootArgs();
    }
}
