// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GithubWorkflow.Inputs
{

    public sealed class A3 : global::Pulumi.InvokeArgs
    {
        [Input("run")]
        public Inputs.A1? Run { get; set; }

        public A3()
        {
        }
        public static new A3 Empty => new A3();
    }
}
