// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GithubWorkflow.Inputs
{

    public sealed class A3Args : global::Pulumi.ResourceArgs
    {
        [Input("run")]
        public Input<Inputs.A1Args>? Run { get; set; }

        public A3Args()
        {
        }
        public static new A3Args Empty => new A3Args();
    }
}
