// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GithubWorkflow.Inputs
{

    public sealed class Definitions_defaults_runArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// unhandled schema: Json.Schema.CommentKeyword, Json.Schema.DescriptionKeyword, Json.Schema.AnyOfKeyword
        /// </summary>
        [Input("shell")]
        public Input<object>? Shell { get; set; }

        /// <summary>
        /// Using the working-directory keyword, you can specify the working directory of where to run the command.
        /// </summary>
        [Input("working-directory")]
        public Input<string>? Working-directory { get; set; }

        public Definitions_defaults_runArgs()
        {
        }
        public static new Definitions_defaults_runArgs Empty => new Definitions_defaults_runArgs();
    }
}
