// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.GithubWorkflow.Inputs
{

    public sealed class DefinitionsDefaultsArgs : global::Pulumi.ResourceArgs
    {
        [Input("run")]
        public Input<Inputs.DefinitionsDefaultsRunArgs>? Run { get; set; }

        public DefinitionsDefaultsArgs()
        {
        }
        public static new DefinitionsDefaultsArgs Empty => new DefinitionsDefaultsArgs();
    }
}
