name: ci

on:
  push:
    branch: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest 
 
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Format
        run: dotnet format

      - name: Build and Test
        if: github.event_name != 'push'
        run: dotnet test -c Debug

      - name: Build, Tests, Cover, Pack and Publish
        if: github.event_name == 'push'
        shell: bash
        run: |
          dotnet tool install --global dotnet-releaser
          dotnet-releaser run --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml